# Site settings
title: titbits generated @random()
header-img: img/home-bg.jpg
email: bargava@gmail.com
description: "A blog to document experiments with the statistical language R"
baseurl: "/r-titbits"
url: "http://github.com/rouesguy"
twitter_username: bargava
github_username:  rouseguy
facebook_username:  bargava
actual_name: Bargava
disqus_shortname: rouseguy

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
