# Site settings
title: R Titbits generated @random()
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "A blog to document experiments with the statistical language R"
baseurl: "/r-titbits"
url: "http://yourdomain.com"
twitter_username: bargava
github_username:  rouseguy
facebook_username:  bargava

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
